executor: slurm
    default-resources:
        partition: componc_cpu,componc_gpu_batch
        nodes: 1
        cpus-per-task: 4
        time: 90:00:00
        mem: 64GB
        mail-user: ahunos@mskcc.org
        mail-type: END,FAIL

set-resources:
    mod_bases:
        slurm_partition: "componc_gpu_batch"
        slurm_account: "greenbab"
        nodes: 1
        runtime: 3400
        slurm_extra: "'--gres=gpu:4'"
        mem_mb_per_cpu: 24000
        cpus_per_task: 8
    sort_mod_bases:
        slurm_partition: "componc_cpu"
        slurm_account: "greenbab"
        nodes: 1
        runtime: 2400
        mem_mb_per_cpu: 24000
        cpus_per_task: 8
    merge_bams:
        slurm_partition: "componc_cpu"
        slurm_account: "greenbab"
        nodes: 1
        runtime: 400
        mem_mb_per_cpu: 24000
        cpus_per_task: 8
    mark_duplicates:
        slurm_partition: "componc_cpu"
        slurm_account: "greenbab"
        nodes: 1
        runtime: 2400
        mem_mb_per_cpu: 24000
        cpus_per_task: 8

    # short_cpu_jobs:
    #     partition: cpushort
    #     nodes: 1
    #     cpus-per-task: 4
    #     time: 02:00:00
    #     mem: 32GB
    #     mail-user: ahunos@mskcc.org
    #     mail-type: END,FAIL
    # short_gpu_jobs:
    #     partition: gpushort
    #     nodes: 1
    #     cpus-per-task: 4
    #     time: 02:00:00
    #     mem: 32GB
    #     mail-user: ahunos@mskcc.org
    #     mail-type: END,FAIL    
    # high_mem_cpu_jobs:
    #     partition: componc_cpu
    #     nodes: 1
    #     cpus-per-task: 4
    #     time: 60:00:00
    #     mem: 64GB
    #     mail-user: ahunos@mskcc.org
    #     mail-type: END,FAIL